version: "3.8"

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/chanwopa/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/chanwopa/data/mariadb

services:
  mariadb:
    container_name: mariadb
    image: mariadb:custom
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress:custom
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:custom
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: unless-stopped
